#!/bin/bash
# Quick Test Guide - Shift Status & Day View Fix

echo "=========================================="
echo "🧪 QUICK TEST GUIDE"
echo "=========================================="
echo ""

echo "✅ STEP 1: Open Browser"
echo "Open: http://localhost/aplikasi/kalender.php"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "✅ STEP 2: Select Cabang & Shift"
echo "1. Select a cabang from dropdown"
echo "2. Select a shift (e.g., Pagi, Siang)"
echo "3. Verify shift dropdown is populated"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "✅ STEP 3: Test Month View"
echo "Expected:"
echo "- See shift assignments with status badges"
echo "- ✓ for approved (green)"
echo "- ⏱ for pending (orange)"
echo "- ✗ for declined (red)"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "✅ STEP 4: Test Day View"
echo "1. Click on a date in month view"
echo "2. Should switch to day view"
echo "3. Expected:"
echo "   - Shifts appear at CORRECT time (e.g., 08:00 for Shift Pagi)"
echo "   - NOT all at 00:00-08:00"
echo "   - Status badges visible"
echo "   - Color coding: green (approved), orange (pending), red (declined)"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "✅ STEP 5: Test Week View"
echo "1. Click 'Minggu' button"
echo "2. Expected:"
echo "   - See 7 days (Mon-Sun)"
echo "   - Each day shows shift summary with status"
echo "   - Status icons visible"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "✅ STEP 6: Test Assign Shift"
echo "1. In day view, click on a time slot (e.g., 08:00)"
echo "2. Modal should open"
echo "3. Select pegawai (can select multiple)"
echo "4. Click 'Assign Shift'"
echo "5. Expected:"
echo "   - Success message"
echo "   - New shift appears at clicked time"
echo "   - Status = pending (⏱)"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "✅ STEP 7: Test Table View"
echo "Open: http://localhost/aplikasi/shift_management.php"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "✅ STEP 8: Check Status in Table"
echo "Expected:"
echo "- Status column shows badges"
echo "- Approved shifts have 🔒 Locked button (disabled)"
echo "- Pending/declined shifts have [Hapus] button (enabled)"
echo "- Approved rows have gray background"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "✅ STEP 9: Test Delete Protection"
echo "1. Try to click 🔒 Locked button"
echo "2. Expected: Nothing happens (disabled)"
echo "3. Try to delete pending shift"
echo "4. Expected: Confirmation, then deleted"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "✅ STEP 10: Manual Status Test (Database)"
echo "Run this SQL to approve a shift:"
echo ""
echo "UPDATE shift_assignments"
echo "SET status_konfirmasi = 'approved', waktu_konfirmasi = NOW()"
echo "WHERE id = <your_test_id>;"
echo ""
echo "Then refresh browser and verify:"
echo "- Badge changes to ✓ Approved (green)"
echo "- Delete button becomes 🔒 Locked"
echo "- Row background becomes gray"
echo ""
read -p "Press ENTER when ready..."

echo ""
echo "=========================================="
echo "🎉 TEST COMPLETE!"
echo "=========================================="
echo ""
echo "✅ All tests passed?"
read -p "Enter 'yes' if all good: " answer

if [ "$answer" = "yes" ]; then
    echo ""
    echo "🎊 CONGRATULATIONS!"
    echo "✨ All features are working correctly!"
    echo ""
    echo "Summary:"
    echo "✅ Status display in all views"
    echo "✅ Day view time slot positioning"
    echo "✅ Lock mechanism for approved shifts"
    echo "✅ Color coding and badges"
    echo "✅ Backend API protection"
    echo ""
    echo "🚀 System is production-ready!"
else
    echo ""
    echo "⚠️  Some tests failed. Please check:"
    echo "1. Browser console for JS errors"
    echo "2. PHP error logs"
    echo "3. Database status_konfirmasi column"
    echo "4. Apache/MySQL are running"
    echo ""
    echo "Logs location:"
    echo "- PHP: /Applications/XAMPP/xamppfiles/logs/error_log"
    echo "- MySQL: /Applications/XAMPP/xamppfiles/logs/mysql_error.log"
fi

echo ""
echo "=========================================="
